apiVersion: apps/v1
kind: Deployment
metadata:
  name: etzhaellaweb-deployment
  labels:
    app: etzhaellaweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etzhaellaweb
  template:
    metadata:
      labels:
        app: etzhaellaweb
    spec:
      containers:
      - name: etzhaellaweb
        image: etzhaella/etzhaellaweb:latest   # ← כאן התמונה שלך מדוקר
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred   # ← זה ה-secret שיצרת עם kubectl
